#!/usr/bin/env python3
import sys
import os
# Dodajemy katalog src do ścieżki wyszukiwania modułów
sys.path.append(os.path.join(os.getcwd(), "src"))
from main import main
if __name__ == "__main__":
    main()
