#!/usr/bin/env python3
import sys
import os
# Ustawienie ścieżki, aby python widział moduły w bieżącym katalogu
sys.path.append(os.getcwd())
from main import main
if __name__ == "__main__":
    main()
